# Generated by Django 3.0.4 on 2020-09-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200708_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="I'm now part of Prodigo :D"),
        ),
    ]
