# Generated by Django 3.0.5 on 2020-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0002_auto_20200508_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True, verbose_name='number of credits'),
        ),
    ]
