# Generated by Django 3.0.5 on 2020-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0003_auto_20200508_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='credit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='number of credits'),
        ),
    ]
