# Generated by Django 3.0.5 on 2020-05-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0004_auto_20200508_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='do.Credit'),
        ),
    ]
