# Generated by Django 3.0.5 on 2020-05-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0005_auto_20200508_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit',
        ),
    ]
